version: "3.9"
services:
    db:
        image: postgres
        container_name: DB_ECOMMERCE
        restart: always
        volumes:
            - db_data:/var/lib/db
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    redis:
        image: redis:7.0
        container_name: redis
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - redis
        restart: always
        ports:
            - "8080:8080"

volumes:
    db_data:
    redis_data:
