// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/NghiaLeopard/Go-Ecommerce-Backend/internal/api"
	"github.com/NghiaLeopard/Go-Ecommerce-Backend/internal/api/handler"
	"github.com/NghiaLeopard/Go-Ecommerce-Backend/internal/usecase"
	"github.com/NghiaLeopard/Go-Ecommerce-Backend/pkg/config"
)

// Injectors from wire.go:

func InitApi(db *sql.DB, config2 config.Config) (*api.ServerHTTP, error) {
	iAuthUseCase := usecase.NewAuthUseCase(db)
	iAuthHandler := handler.NewAuthHandler(iAuthUseCase)
	serverHTTP := api.NewServerHTTP(config2, iAuthHandler)
	return serverHTTP, nil
}
