// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: City.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createCity = `-- name: CreateCity :one
INSERT INTO "City" (
  name
) VALUES (
  $1
)
RETURNING id, name
`

func (q *Queries) CreateCity(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, name)
	var i City
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteCityById = `-- name: DeleteCityById :exec
DELETE FROM "City"
WHERE id = $1
`

func (q *Queries) DeleteCityById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCityById, id)
	return err
}

const deleteManyCityByIds = `-- name: DeleteManyCityByIds :exec
DELETE FROM "City"
WHERE id = ANY($1::bigint[])
`

func (q *Queries) DeleteManyCityByIds(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.ExecContext(ctx, deleteManyCityByIds, pq.Array(dollar_1))
	return err
}

const getCity = `-- name: GetCity :one
SELECT id, name FROM "City"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCity(ctx context.Context, id int64) (City, error) {
	row := q.db.QueryRowContext(ctx, getCity, id)
	var i City
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCity = `-- name: ListCity :many
SELECT id, name FROM "City"
WHERE name ILIKE '%' || $1 || '%'
ORDER BY $2
LIMIT $3
OFFSET $4
`

type ListCityParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 interface{}    `json:"column_2"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) ListCity(ctx context.Context, arg ListCityParams) ([]City, error) {
	rows, err := q.db.QueryContext(ctx, listCity,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []City{}
	for rows.Next() {
		var i City
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :one
UPDATE "City" SET name = $1
WHERE id = $2
RETURNING id, name
`

type UpdateCityParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, updateCity, arg.Name, arg.ID)
	var i City
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
