// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID                   int64          `json:"id"`
	Email                string         `json:"email"`
	Password             string         `json:"password"`
	ResetToken           sql.NullString `json:"resetToken"`
	ResetTokenExpiration sql.NullTime   `json:"resetTokenExpiration"`
	CreateAt             time.Time      `json:"create_at"`
}
