// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ProductStatus string

const (
	ProductStatus0 ProductStatus = "0"
	ProductStatus1 ProductStatus = "1"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type UsersStatus string

const (
	UsersStatus0 UsersStatus = "0"
	UsersStatus1 UsersStatus = "1"
)

func (e *UsersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersStatus(s)
	case string:
		*e = UsersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersStatus: %T", src)
	}
	return nil
}

type NullUsersStatus struct {
	UsersStatus UsersStatus `json:"users_status"`
	Valid       bool        `json:"valid"` // Valid is true if UsersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UsersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersStatus), nil
}

type UsersType string

const (
	UsersType1 UsersType = "1"
	UsersType2 UsersType = "2"
	UsersType3 UsersType = "3"
)

func (e *UsersType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersType(s)
	case string:
		*e = UsersType(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersType: %T", src)
	}
	return nil
}

type NullUsersType struct {
	UsersType UsersType `json:"users_type"`
	Valid     bool      `json:"valid"` // Valid is true if UsersType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersType) Scan(value interface{}) error {
	if value == nil {
		ns.UsersType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersType), nil
}

type City struct {
	ID       int64     `json:"id"`
	Name     string    `json:"name"`
	CreateAt time.Time `json:"create_at"`
	UpdateAt time.Time `json:"update_at"`
}

type Product struct {
	ID                int64             `json:"id"`
	Name              string            `json:"name"`
	Image             string            `json:"image"`
	CountInStock      int32             `json:"countInStock"`
	Description       string            `json:"description"`
	Sold              sql.NullInt32     `json:"sold"`
	Discount          sql.NullInt32     `json:"discount"`
	DiscountStartDate sql.NullTime      `json:"discountStartDate"`
	DiscountEndDate   sql.NullTime      `json:"discountEndDate"`
	Type              int32             `json:"type"`
	Status            NullProductStatus `json:"status"`
	Slug              string            `json:"slug"`
	Views             sql.NullInt32     `json:"views"`
	Price             int32             `json:"price"`
	Location          string            `json:"location"`
}

type ProductLiked struct {
	ProductID int32     `json:"product_id"`
	UserID    int32     `json:"user_id"`
	CreateAt  time.Time `json:"create_at"`
}

type ProductType struct {
	ID       int64        `json:"id"`
	Name     string       `json:"name"`
	Slug     string       `json:"slug"`
	CreateAt time.Time    `json:"create_at"`
	UpdateAt sql.NullTime `json:"update_at"`
}

type ProductUniqueView struct {
	ProductID int32        `json:"product_id"`
	UserID    int32        `json:"user_id"`
	ViewDate  sql.NullTime `json:"view_date"`
}

type Role struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Permission []string  `json:"permission"`
	CreateAt   time.Time `json:"create_at"`
	UpdateAt   time.Time `json:"update_at"`
}

type User struct {
	ID                   int64                 `json:"id"`
	Email                string                `json:"email"`
	Password             string                `json:"password"`
	ResetToken           sql.NullString        `json:"resetToken"`
	UserType             NullUsersType         `json:"userType"`
	Status               NullUsersStatus       `json:"status"`
	Address              sql.NullString        `json:"address"`
	Avatar               sql.NullString        `json:"avatar"`
	PhoneNumber          sql.NullInt64         `json:"phoneNumber"`
	Role                 sql.NullInt64         `json:"role"`
	FirstName            sql.NullString        `json:"firstName"`
	LastName             sql.NullString        `json:"lastName"`
	MiddleName           sql.NullString        `json:"middleName"`
	City                 sql.NullInt64         `json:"city"`
	LikeProducts         []int64               `json:"likeProducts"`
	ViewedProducts       []int64               `json:"viewedProducts"`
	DeviceToken          []string              `json:"deviceToken"`
	Addresses            pqtype.NullRawMessage `json:"addresses"`
	ResetTokenExpiration sql.NullTime          `json:"resetTokenExpiration"`
	CreateAt             time.Time             `json:"create_at"`
}
