// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: Product_Unique.sql

package db

import (
	"context"
)

const createProductView = `-- name: CreateProductView :one
INSERT INTO "Product_UniqueView" (
  "product_id","user_id"
) VALUES (
  $1, $2
)
RETURNING product_id, user_id, view_date, create_at
`

type CreateProductViewParams struct {
	ProductID int32 `json:"product_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) CreateProductView(ctx context.Context, arg CreateProductViewParams) (ProductUniqueView, error) {
	row := q.db.QueryRowContext(ctx, createProductView, arg.ProductID, arg.UserID)
	var i ProductUniqueView
	err := row.Scan(
		&i.ProductID,
		&i.UserID,
		&i.ViewDate,
		&i.CreateAt,
	)
	return i, err
}
