// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRole(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetRole(ctx context.Context, id int64) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	InitDefaultAdmin(ctx context.Context, arg InitDefaultAdminParams) (User, error)
	ListRole(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePasswordUser(ctx context.Context, arg UpdatePasswordUserParams) error
}

var _ Querier = (*Queries)(nil)
