// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateCity(ctx context.Context, name string) (City, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCity(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCity(ctx context.Context, id int64) (City, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	InitDefaultAdmin(ctx context.Context, arg InitDefaultAdminParams) (User, error)
	ListCity(ctx context.Context, arg ListCityParams) ([]City, error)
	ListRole(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context) ([]User, error)
	SaveResetToken(ctx context.Context, arg SaveResetTokenParams) (User, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error)
	UpdatePasswordUser(ctx context.Context, arg UpdatePasswordUserParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
