// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: Users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "Users" (
  email, password
) VALUES (
  $1, $2
)
RETURNING id, email, password, "resetToken", status, address, avatar, "phoneNumber", role, "firstName", "lastName", "middleName", city, "likeProducts", "viewedProducts", addresses, "resetTokenExpiration", create_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.ResetToken,
		&i.Status,
		&i.Address,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.LikeProducts,
		&i.ViewedProducts,
		&i.Addresses,
		&i.ResetTokenExpiration,
		&i.CreateAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "Users"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const findEmail = `-- name: FindEmail :one
SELECT id, email, password, "resetToken", status, address, avatar, "phoneNumber", role, "firstName", "lastName", "middleName", city, "likeProducts", "viewedProducts", addresses, "resetTokenExpiration", create_at FROM "Users"
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.ResetToken,
		&i.Status,
		&i.Address,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.LikeProducts,
		&i.ViewedProducts,
		&i.Addresses,
		&i.ResetTokenExpiration,
		&i.CreateAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password, "resetToken", status, address, avatar, "phoneNumber", role, "firstName", "lastName", "middleName", city, "likeProducts", "viewedProducts", addresses, "resetTokenExpiration", create_at FROM "Users"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.ResetToken,
		&i.Status,
		&i.Address,
		&i.Avatar,
		&i.PhoneNumber,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.City,
		&i.LikeProducts,
		&i.ViewedProducts,
		&i.Addresses,
		&i.ResetTokenExpiration,
		&i.CreateAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password, "resetToken", status, address, avatar, "phoneNumber", role, "firstName", "lastName", "middleName", city, "likeProducts", "viewedProducts", addresses, "resetTokenExpiration", create_at FROM "Users"
ORDER BY create_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.ResetToken,
			&i.Status,
			&i.Address,
			&i.Avatar,
			&i.PhoneNumber,
			&i.Role,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.City,
			&i.LikeProducts,
			&i.ViewedProducts,
			&i.Addresses,
			&i.ResetTokenExpiration,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
