// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: City.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createCity = `-- name: CreateCity :one
INSERT INTO "City" (
  name
) VALUES (
  $1
)
RETURNING _id, name, create_at, update_at
`

func (q *Queries) CreateCity(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRowContext(ctx, createCity, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const deleteCityById = `-- name: DeleteCityById :exec
DELETE FROM "City"
WHERE "_id" = $1
`

func (q *Queries) DeleteCityById(ctx context.Context, ID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCityById, ID)
	return err
}

const deleteManyCityByIds = `-- name: DeleteManyCityByIds :exec
DELETE FROM "City"
WHERE "_id" = ANY($1::bigint[])
`

func (q *Queries) DeleteManyCityByIds(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.ExecContext(ctx, deleteManyCityByIds, pq.Array(dollar_1))
	return err
}

const getCityById = `-- name: GetCityById :one
SELECT _id, name, create_at, update_at FROM "City"
WHERE "_id" = $1 LIMIT 1
`

func (q *Queries) GetCityById(ctx context.Context, ID int64) (City, error) {
	row := q.db.QueryRowContext(ctx, getCityById, ID)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getCityByName = `-- name: GetCityByName :one
SELECT _id, name, create_at, update_at FROM "City"
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetCityByName(ctx context.Context, name string) (City, error) {
	row := q.db.QueryRowContext(ctx, getCityByName, name)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const listCity = `-- name: ListCity :many
SELECT _id, name, create_at, update_at,COUNT("City"."_id") OVER() AS "totalCount" FROM "City"
WHERE  $1 ::text = '' or name ILIKE concat('%',$1,'%')
ORDER BY 
  CASE 
        WHEN $2 ::varchar = 'name asc' THEN name END ASC,
  CASE 
        WHEN $2 = 'name desc' THEN name END DESC
LIMIT NULLIF($4 :: int, 0)
OFFSET NULLIF($3 :: int, 0)
`

type ListCityParams struct {
	Search    string `json:"search"`
	OrderBy   string `json:"order_by"`
	OffsetOpt int32  `json:"offset_opt"`
	LimitOpt  int32  `json:"limit_opt"`
}

type ListCityRow struct {
	ID         int64     `json:"_id"`
	Name       string    `json:"name"`
	CreateAt   time.Time `json:"create_at"`
	UpdateAt   time.Time `json:"update_at"`
	TotalCount int64     `json:"totalCount"`
}

func (q *Queries) ListCity(ctx context.Context, arg ListCityParams) ([]ListCityRow, error) {
	rows, err := q.db.QueryContext(ctx, listCity,
		arg.Search,
		arg.OrderBy,
		arg.OffsetOpt,
		arg.LimitOpt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCityRow{}
	for rows.Next() {
		var i ListCityRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreateAt,
			&i.UpdateAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCity = `-- name: UpdateCity :one
UPDATE "City" SET name = $1,update_at = NOW()
WHERE "_id" = $2
RETURNING _id, name, create_at, update_at
`

type UpdateCityParams struct {
	Name string `json:"name"`
	ID   int64  `json:"_id"`
}

func (q *Queries) UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error) {
	row := q.db.QueryRowContext(ctx, updateCity, arg.Name, arg.ID)
	var i City
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}
