// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: DeliveryType.sql

package db

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO "Delivery_Type" (
  name,price
) VALUES (
  $1,$2
)
RETURNING _id, name, price, "createAt", update_at
`

type CreateDeliveryParams struct {
	Name  string `json:"name"`
	Price int32  `json:"price"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (DeliveryType, error) {
	row := q.db.QueryRowContext(ctx, createDelivery, arg.Name, arg.Price)
	var i DeliveryType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const deleteDeliveryById = `-- name: DeleteDeliveryById :exec
DELETE FROM "Delivery_Type"
WHERE "_id" = $1
`

func (q *Queries) DeleteDeliveryById(ctx context.Context, ID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryById, ID)
	return err
}

const deleteManyDeliveryByIds = `-- name: DeleteManyDeliveryByIds :exec
DELETE FROM "Delivery_Type"
WHERE "_id" = ANY($1::bigint[])
`

func (q *Queries) DeleteManyDeliveryByIds(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.ExecContext(ctx, deleteManyDeliveryByIds, pq.Array(dollar_1))
	return err
}

const getDeliveryById = `-- name: GetDeliveryById :one
SELECT _id, name, price, "createAt", update_at FROM "Delivery_Type"
WHERE "_id" = $1 LIMIT 1
`

func (q *Queries) GetDeliveryById(ctx context.Context, ID int64) (DeliveryType, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryById, ID)
	var i DeliveryType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getDeliveryByName = `-- name: GetDeliveryByName :one
SELECT _id, name, price, "createAt", update_at FROM "Delivery_Type"
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetDeliveryByName(ctx context.Context, name string) (DeliveryType, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryByName, name)
	var i DeliveryType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const listDelivery = `-- name: ListDelivery :many
SELECT _id, name, price, "createAt", update_at,COUNT("Delivery_Type"."_id") OVER() AS "totalCount" FROM "Delivery_Type"
WHERE  $1 ::text = '' or name ILIKE concat('%',$1,'%')
ORDER BY 
  CASE 
        WHEN $2 ::varchar = 'name asc' THEN name END ASC,
  CASE 
        WHEN $2 = 'name desc' THEN name END DESC
LIMIT NULLIF($4 :: int, 0)
OFFSET NULLIF($3 :: int, 0)
`

type ListDeliveryParams struct {
	Search    string `json:"search"`
	OrderBy   string `json:"order_by"`
	OffsetOpt int32  `json:"offset_opt"`
	LimitOpt  int32  `json:"limit_opt"`
}

type ListDeliveryRow struct {
	ID         int64     `json:"_id"`
	Name       string    `json:"name"`
	Price      int32     `json:"price"`
	CreateAt   time.Time `json:"createAt"`
	UpdateAt   time.Time `json:"update_at"`
	TotalCount int64     `json:"totalCount"`
}

func (q *Queries) ListDelivery(ctx context.Context, arg ListDeliveryParams) ([]ListDeliveryRow, error) {
	rows, err := q.db.QueryContext(ctx, listDelivery,
		arg.Search,
		arg.OrderBy,
		arg.OffsetOpt,
		arg.LimitOpt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveryRow{}
	for rows.Next() {
		var i ListDeliveryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.CreateAt,
			&i.UpdateAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelivery = `-- name: UpdateDelivery :one
UPDATE "Delivery_Type" SET name = $1,price = $1,update_at = NOW()
WHERE "_id" = $2
RETURNING _id, name, price, "createAt", update_at
`

type UpdateDeliveryParams struct {
	Name string `json:"name"`
	ID   int64  `json:"_id"`
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (DeliveryType, error) {
	row := q.db.QueryRowContext(ctx, updateDelivery, arg.Name, arg.ID)
	var i DeliveryType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}
