// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateCity(ctx context.Context, name string) (City, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductLike(ctx context.Context, arg CreateProductLikeParams) error
	CreateProductType(ctx context.Context, arg CreateProductTypeParams) (ProductType, error)
	CreateProductUniqueView(ctx context.Context, arg CreateProductUniqueViewParams) error
	CreateRole(ctx context.Context, name string) (Role, error)
	CreateRoleByDefault(ctx context.Context, arg CreateRoleByDefaultParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCityById(ctx context.Context, id int64) error
	DeleteLikedProductByUserId(ctx context.Context, userID int32) error
	DeleteManyCityByIds(ctx context.Context, dollar_1 []int64) error
	DeleteManyProductTypesByIds(ctx context.Context, dollar_1 []int64) error
	DeleteManyProductsByIds(ctx context.Context, dollar_1 []int64) error
	DeleteManyRolesByIds(ctx context.Context, dollar_1 []int64) error
	DeleteProductById(ctx context.Context, id int64) error
	DeleteProductTypeById(ctx context.Context, id int64) error
	DeleteRoleById(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	FindUserById(ctx context.Context, id int64) error
	GetAllProductLike(ctx context.Context, userID int32) (GetAllProductLikeRow, error)
	GetAllProductView(ctx context.Context, userID int32) (GetAllProductViewRow, error)
	GetCityById(ctx context.Context, id int64) (City, error)
	GetCityByName(ctx context.Context, name string) (City, error)
	GetProductById(ctx context.Context, id int64) (GetProductByIdRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetProductPublicById(ctx context.Context, id int64) (GetProductPublicByIdRow, error)
	GetProductRelated(ctx context.Context, arg GetProductRelatedParams) (GetProductRelatedRow, error)
	GetProductTypeById(ctx context.Context, id int64) (ProductType, error)
	GetProductTypeByName(ctx context.Context, name string) (ProductType, error)
	GetRoleById(ctx context.Context, id int64) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	InitDefaultAdmin(ctx context.Context, arg InitDefaultAdminParams) (User, error)
	ListCity(ctx context.Context, arg ListCityParams) ([]City, error)
	ListProductType(ctx context.Context, arg ListProductTypeParams) ([]ProductType, error)
	ListRole(ctx context.Context, arg ListRoleParams) ([]Role, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAuthMe(ctx context.Context, arg UpdateAuthMeParams) (User, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error)
	UpdatePasswordUser(ctx context.Context, arg UpdatePasswordUserParams) error
	UpdateProductType(ctx context.Context, arg UpdateProductTypeParams) (ProductType, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateViewProduct(ctx context.Context, arg UpdateViewProductParams) error
}

var _ Querier = (*Queries)(nil)
