basePath: /api
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: nghiabeo1605@gmail.com
    name: Nguyễn Đại Nghĩa
    url: https://www.facebook.com/shy.leopard.beo
  description: This is a server ecommerce.
  title: Swagger Golang Ecommerce
paths: {}
swagger: "2.0"
